module.exports = [
"Abu",
"Al & Andy",
"Aladdin",
"Alan M. Mayberry",
"Alexander Cabot III",
"Alvin",
"Angelica Pickles",
"Archie",
"Arthur",
"Astro",
"Atom Ant",
"Bagheera & Akela",
"Baloo",
"Bamm-Bamm",
"Barney Rubble",
"Bart Simpson",
"Batman",
"Beavis",
"Beetle Baily",
"Betty Boop",
"Betty McBrickner Rubble",
"Bevis and Butthead",
"Bill",
"Blip",
"Blondie",
"Blossom",
"Bobby Hill",
"Boo Boo",
"Boris Badenov",
"Brak",
"Breezly",
"Bubbles",
"Bullseye & Bo Peep",
"Bullwinkle",
"Butt-head",
"Buttercup",
"Buzz Lightyear",
"Calvin",
"Cap'n Crunch",
"Captain America",
"Cartman",
"Casper the Friendly Ghost",
"Cat in the Hat",
"Cat Woman",
"Charlie Brown",
"Charlie Tuna",
"Chester Cheetah",
"Chief Winchley",
"Chip and Dale",
"Chopper",
"Chuck",
"Cinderella",
"Cindy Bear",
"Clifford the Big Red Dog",
"Coil Man",
"Colonel Hathi",
"Cosmo S. Spacely",
"Crush",
"Curious George",
"Dagwood",
"Daisy Duck",
"Daphne Blake",
"Darla",
"Dash",
"Dee Dee",
"Dennis the Menace",
"Dexter",
"Dick Tracy",
"Dilbert",
"Ding-A-Ling",
"Dino",
"Dino Boy",
"Dixie",
"Dora the Explorer",
"Dorno",
"Dory",
"Dr. Benton",
"Drizella & Anastasia",
"Droop-A-Long",
"Droopy the Dog",
"Duckworth the Butler",
"Dudley Dooright",
"Edna",
"Eeyore",
"Elastigirl",
"Elroy Jetson",
"Fairy Godmother (Cinderella)",
"Fantastic Four",
"Fat Albert",
"Felix the Cat",
"Fibber Fox",
"Flash",
"Floral Rugg",
"Fluid Man",
"Foghorn Leghorn",
"Fred Freddie Jones",
"Fred Flintstone",
"Fritz the cat",
"Frosty",
"Frozone",
"Genie",
"George Nate Slate",
"Gerald McBoing-Boing",
"Ghost Rider",
"Gill",
"Gloop and Gleep",
"Grape Ape",
"Green Giant",
"Grimm",
"Grinch",
"Gumby",
"Hadji",
"Hagar the Horrible",
"Heckle and Jeckle",
"Hellboy",
"Hello Kitty",
"Hobbes",
"Hokey Wolf",
"Homer Simpson",
"Hoppy",
"Huckleberry Hound",
"Huey, Dewey, Louie",
"Igoo",
"Iron Man",
"Jace",
"Jack-Jack",
"Jan",
"Jane Jetson",
"Jaq & Gus",
"Jerry",
"Jessie",
"Jet Screame",
"Joe Camel",
"Johnny Bravo",
"Jonny Quest",
"Josie McCoy",
"Judy Jetson",
"Jughead",
"Kaboobie",
"Kenny from South Park",
"King Louie",
"Lady Tremaine",
"Launchpad McQuack",
"Lil' Abner",
"Linus",
"Lippy the Lion & Hardy Har Har",
"Lisa Simpson",
"Lucky from Charlie Brown",
"Lucy",
"Maggie Simpson",
"Magic Carpet",
"Magica De Spell",
"Magilla Gorilla",
"Mandark",
"Marge Simpson",
"Marlin",
"Marmaduke",
"Marvin Martian",
"Maw Rugg",
"Melody Valentine",
"Mighty Mouse",
"Minnie Mouse",
"Mirage",
"Moby Dick",
"Mojo Jojo",
"Morocco Mole",
"Mowgli & Shanti",
"Mr. & Mrs. Potatohead",
"Mr. Incredible",
"Mr. Jinks",
"Mr. Kool-Aid",
"Mr. Magoo",
"Mr. Peebles",
"Multi Man",
"Mushmouse",
"Muttley",
"Nancy",
"Natasha Fatale",
"Nemo",
"Nigel",
"Norville Shaggy Rogers",
"Ogee",
"Olive Oyl",
"Paw Rugg",
"Pebbles Flintstone",
"Pepé lePew",
"Peter Griffith",
"Peter Pan",
"Peter Potamus",
"Piglet",
"Pikachu",
"Pink Panther",
"Pinky and the Brain",
"Pixie",
"Pluto",
"Popeye",
"Porky Pig",
"Prince Charming",
"Princess Jasmine",
"Punkin Puss",
"Ranger Smith",
"Red Hot",
"Ren and Stimpy",
"Rex",
"Richie Rich",
"Ricochet Rabbit",
"Road Runner",
"Robin",
"Rocky",
"Roger Rabbit",
"Rosie the Robot",
"Sad Sack",
"Santa's Little Helper",
"Scoobert Scooby Doo",
"Scooby the Seal",
"Scooby-Dee",
"Scooby-Doo",
"Scooby-Dum",
"Scrappy Doo",
"Scrooge McDuck",
"Secret Squirrel",
"Shag Rugg",
"Shaggy from the Scooby-Doo",
"Shazzan",
"Shere Khan",
"Sheriff Woody",
"Sherman",
"Slinky Dog",
"Smurfs",
"Snagglepuss",
"Snap, Crackle and Pop",
"Sneezly",
"Snidely Whiplash",
"Snoopy",
"Snuffles",
"SoSo",
"Space",
"Space Ghost",
"Speed Buggy",
"Speed Racer",
"Spiderman",
"Spike the Bulldog",
"SpongeBob SquarePants",
"Squiddly Diddly",
"Superman",
"Sylvester",
"Tara",
"T.Turanga Leela",
"Tasmanian Devil",
"The Beagle Boys",
"The Chief",
"The Great Gazoo",
"The Grinch",
"The Gruesomes",
"The Incredible Hulk",
"The Joker",
"The Professor",
"The Sultan",
"Theo",
"Tigger",
"Tom and Jerry",
"Tom Terrific",
"Tommy Pickles",
"Tony Tiger",
"Top Cat",
"Toucan Sam",
"Touché Turtle and DumDum",
"Transformers",
"Tundro",
"Tweety Bird",
"Ugh the Caveman",
"Underdog",
"Valerie Brown",
"Velma Dinkley",
"Violet",
"Wally Gator",
"Wile E. Coyote",
"Wilma Slaghoople Flintstone",
"Winnie the Pooh",
"Winsome Witch",
"Wolverine",
"Wonder Woman",
"Woodstock",
"Woody Woodpecker",
"X-Men",
"Yahooey",
"Yakky Doodle",
"Yappee",
"Yippee",
"Yogi Bear",
"Yosemite Sam",
"Zandor",
"Zok",
"Zorak"];